function config = activate_epochs( epoch_names, config )

%   ACTIVATE_EPOCHS -- Update which epochs will be loaded by get_signals().
%
%     IN:
%       - `epoch_names` (cell array of strings, char)
%       - `config` (struct) |OPTIONAL| -- opts as generated by
%        dsp2.config.create().
%     OUT:
%       - `config` (struct) -- Options struct with the specified epochs
%         inactivated.

if ( nargin < 2 )
  config = dsp2.config.load();
end

EPOCHS = config.SIGNALS.EPOCHS;

if ( isequal(epoch_names, 'all') )
  epoch_names = fieldnames( EPOCHS );
else
  epoch_names = unique( dsp2.util.general.ensure_cell(epoch_names) );
  dsp2.util.assertions.assert__are_fields( EPOCHS, epoch_names );
end

for i = 1:numel(epoch_names)
  current = epoch_names{i};
  config.SIGNALS.EPOCHS.(current).active = true;
end

end